[project]
name = "grigoreva_python_hw"
description = "Углубленный python. Домашние работы."
readme = "README.md"
requires-python = ">=3.9"
version = "1.2"

[tool.grigoreva_python_hw]
dependencies = [
    "click==8.1.8",
    "pdflatex==0.1.3",
    "my-latex-cute-lib==1.4"
]