version: '3.9'

services:
  latex-pdf-generator:
    build: .
    volumes:
      - .:/converter  # Mount the current directory to /app inside the container
    environment:
      - DISPLAY=host.docker.internal:0  # If you're on Windows, this might be required to run LaTeX tools with GUI access
    stdin_open: true
    tty: true
